options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/finaflow-backend', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/finaflow-backend']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'finaflow-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/finaflow-backend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - 'trivihair:us-central1:finaflow-db'
      - '--set-env-vars'
      - 'DATABASE_URL=postgresql://finaflow_user:finaflow_password@/finaflow_db?host=/cloudsql/trivihair:us-central1:finaflow-db,SECRET_KEY=finaflow-secret-key-2024,JWT_SECRET=finaflow-secret-key-2024,CORS_ORIGINS=https://finaflow.vercel.app,ALLOWED_HOSTS=finaflow.vercel.app,PROJECT_ID=trivihair'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '600'
      - '--concurrency'
      - '80'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--cpu-boost'

images:
  - 'gcr.io/$PROJECT_ID/finaflow-backend'

timeout: '1200s'
