apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: finaflow-backend
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/startup-cpu-boost: "true"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/automatizar-452311/finaflow-backend
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: "sqlite:///./finaflow.db"
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
