steps:
  # Build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/finaflow-backend:$COMMIT_SHA', './backend']
  
  # Push da imagem para Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/finaflow-backend:$COMMIT_SHA']
  
  # Deploy no Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'finaflow-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/finaflow-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'DATABASE_URL=$_DATABASE_URL,JWT_SECRET=$_JWT_SECRET,CORS_ORIGINS=$_CORS_ORIGINS'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'

# Substituições
substitutions:
  _DATABASE_URL: 'postgresql://finaflow:password@10.0.0.3:5432/finaflow'
  _JWT_SECRET: 'finaflow-super-secret-jwt-key-2024'
  _CORS_ORIGINS: 'https://finaflow.vercel.app,http://localhost:3000'

# Imagens
images:
  - 'gcr.io/$PROJECT_ID/finaflow-backend:$COMMIT_SHA'

# Timeout
timeout: '1200s'

# Opções
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
